import { useState, useMemo } from 'react';
import { 
  BookOpen, 
  Search, 
  X, 
  ExternalLink, 
  ChevronRight,
  Filter
} from 'lucide-react';
import { SectionId } from '../types';
import { useModalA11y } from '../lib/useModalA11y';

export interface GlossaryTerm {
  id: string;
  term: string;
  acronym?: string;
  category: 'Electrical Physics' | 'Metallurgy & Consumables' | 'Equipment & Components' | 'Joints & Geometry' | 'Safety & Standards';
  standardReference: string;
  definition: string;
  practicalImplication: string;
  relatedSection?: SectionId;
  relatedSectionTitle?: string;
  keyFormulaOrMetric?: string;
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    id: 'smaw',
    term: 'Shielded Metal Arc Welding',
    acronym: 'SMAW / MMA / Process 111',
    category: 'Equipment & Components',
    standardReference: 'AWS A3.0 / ISO 4063: 111',
    definition: 'An arc welding process producing coalescence of metals by heating them with an electric arc between a flux-covered consumable metal electrode and the workpieces.',
    practicalImplication: 'Shielding is produced solely by decomposition of the electrode coating without external shielding gas cylinders, making it the most rugged field welding process.',
    relatedSection: '7.1.1',
    relatedSectionTitle: '7.1.1 Basic Principles'
  },
  {
    id: 'dcep',
    term: 'Direct Current Electrode Positive (Reverse Polarity)',
    acronym: 'DCEP / DCRP',
    category: 'Electrical Physics',
    standardReference: 'AWS A3.0 Clause 3.2',
    definition: 'Direct current welding circuit configuration where the electrode holder is connected to the positive (+) terminal and the workpiece to the negative (-) terminal.',
    practicalImplication: 'Concentrates ~70% of arc heat at the electrode and delivers strong positive ion bombardment to the workpiece, yielding superior penetration and cathodic oxide cleaning.',
    relatedSection: '7.1.6',
    relatedSectionTitle: '7.1.6 Polarity Dynamics',
    keyFormulaOrMetric: 'Heat: 70% Anode (+) / 30% Cathode (-)'
  },
  {
    id: 'dcen',
    term: 'Direct Current Electrode Negative (Straight Polarity)',
    acronym: 'DCEN / DCSP',
    category: 'Electrical Physics',
    standardReference: 'AWS A3.0 Clause 3.2',
    definition: 'Direct current welding circuit configuration where the electrode holder is connected to the negative (-) terminal and the workpiece to the positive (+) terminal.',
    practicalImplication: 'Electrons bombard the base metal creating deep, narrow penetration and faster electrode burn-off rates; ideal for thin sheet metal, buildup, and high deposition.',
    relatedSection: '7.1.6',
    relatedSectionTitle: '7.1.6 Polarity Dynamics',
    keyFormulaOrMetric: 'Heat: 70% Workpiece (+) / 30% Electrode (-)'
  },
  {
    id: 'ocv',
    term: 'Open Circuit Voltage',
    acronym: 'OCV',
    category: 'Electrical Physics',
    standardReference: 'NEMA EW-1 / OSHA 1910.252',
    definition: 'The electrical potential difference (voltage) measured across the output terminals of the welding power source when it is energized and ready, but current is not flowing (prior to arc initiation).',
    practicalImplication: 'Typically ranges from 50V to 90V. High OCV ensures rapid arc striking with tough electrodes like E7018, but poses significant electric shock hazard in damp environments.',
    relatedSection: '7.1.3',
    relatedSectionTitle: '7.1.3 Machine Components',
    keyFormulaOrMetric: 'OCV = 50V – 90V (Operating Arc V = 18V – 36V)'
  },
  {
    id: 'arc-blow',
    term: 'Magnetic Arc Blow',
    category: 'Electrical Physics',
    standardReference: 'AWS Welding Handbook Vol 1',
    definition: 'The undesirable deflection of an electric arc from its intended path caused by magnetic flux imbalances and electromagnetic eddy fields generated by heavy DC current flowing through ferromagnetic metals.',
    practicalImplication: 'Causes excessive spatter, incomplete sidewall fusion, and porosity. Remedied by switching to AC, wrapping cables around the workpiece, or shifting ground clamp location.',
    relatedSection: '7.1.6',
    relatedSectionTitle: '7.1.6 Polarity Dynamics'
  },
  {
    id: 'heat-input',
    term: 'Heat Input Equation',
    category: 'Electrical Physics',
    standardReference: 'AWS D1.1 Clause 5.6',
    definition: 'The measure of electrical energy introduced into the base metal per unit length of the weld bead.',
    practicalImplication: 'Controls the cooling rate of the weld and Heat-Affected Zone (HAZ). Excessive heat input enlarges grain size and reduces toughness; inadequate heat causes cold cracking and lack of fusion.',
    relatedSection: '7.1.2',
    relatedSectionTitle: '7.1.2 Ampere Control',
    keyFormulaOrMetric: 'H = (60 × V × I × η) / (1000 × S) [kJ/mm]'
  },
  {
    id: 'haz',
    term: 'Heat-Affected Zone',
    acronym: 'HAZ',
    category: 'Metallurgy & Consumables',
    standardReference: 'AWS A3.0 Standard Terms',
    definition: 'The portion of the base metal whose mechanical properties and microstructure have been altered by the high thermal energy of welding or cutting, but which has not been melted.',
    practicalImplication: 'Often the weakest region of a welded joint where brittle martensite, hydrogen-induced cracking (HIC), and grain coarsening can occur if interpass temperature is not controlled.',
    relatedSection: '7.1.1',
    relatedSectionTitle: '7.1.1 Basic Principles'
  },
  {
    id: 'slag',
    term: 'Slag',
    category: 'Metallurgy & Consumables',
    standardReference: 'AWS A5.1 / A5.5',
    definition: 'A non-metallic vitreous byproduct formed from the fusion and chemical reaction of the flux coating ingredients and non-metallic impurities during arc welding.',
    practicalImplication: 'Floats to the top of the molten pool to shield the cooling metal from atmospheric nitrogen and oxygen, shapes bead contour, and slows cooling rate. Must be completely deslagged between passes.',
    relatedSection: '7.1.7',
    relatedSectionTitle: '7.1.7 Process Labels & SOP'
  },
  {
    id: 'duty-cycle',
    term: 'Duty Cycle',
    category: 'Equipment & Components',
    standardReference: 'IEC 60974-1 / NEMA EW-1',
    definition: 'The percentage of a 10-minute operational time window that a power source can safely deliver its rated output current without tripping thermal overload protection.',
    practicalImplication: 'A 60% duty cycle at 200A allows 6 minutes of continuous arc welding followed by 4 minutes of idle fan cooling. Exceeding causes transformer coil insulation breakdown.',
    relatedSection: '7.1.4',
    relatedSectionTitle: '7.1.4 5 Machine Types',
    keyFormulaOrMetric: 'T_weld ≤ (Duty % / 100) × 10 min'
  },
  {
    id: 'droop-characteristic',
    term: 'Constant Current (CC / Drooper) Characteristic',
    acronym: 'CC Characteristic',
    category: 'Equipment & Components',
    standardReference: 'AWS D1.1 / ASME IX',
    definition: 'A power source volt-ampere output curve designed so that large variations in arc voltage (caused by unavoidable manual welder hand tremors changing arc length) result in only minimal changes in welding current.',
    practicalImplication: 'Essential for SMAW. Keeps thermal puddle input stable even when the operator slightly lengthens or shortens the arc gap.',
    relatedSection: '7.1.3',
    relatedSectionTitle: '7.1.3 Machine Components',
    keyFormulaOrMetric: 'ΔV large → ΔI minimal (< 5% shift)'
  },
  {
    id: 'electrode-classification',
    term: 'AWS Electrode Classification System (e.g. E7018)',
    category: 'Metallurgy & Consumables',
    standardReference: 'AWS A5.1 / A5.5',
    definition: 'Standard alphanumeric coding specifying electrode characteristics: E (Electrode), first 2 digits (minimum tensile strength in ksi, e.g. 70 = 70,000 psi), third digit (welding position: 1 = all positions), fourth digit (flux coating and electrical current type: 8 = low-hydrogen iron powder, DCEP/AC).',
    practicalImplication: 'Selecting incorrect classification causes understrength welds or hydrogen embrittlement failure in restrained structural joints.',
    relatedSection: '7.1.2',
    relatedSectionTitle: '7.1.2 Ampere Control'
  },
  {
    id: 'low-hydrogen',
    term: 'Low-Hydrogen Electrode Storage & Baking',
    acronym: 'H4R / H8 Classification',
    category: 'Metallurgy & Consumables',
    standardReference: 'AWS D1.1 Clause 5.3.2.2',
    definition: 'Mineral-coated electrodes (E7018, E8018) formulated with potassium/calcium compounds to deposit welds with ≤ 4 to 8 mL of diffusible hydrogen per 100g of weld metal.',
    practicalImplication: 'Must be stored in holding ovens at 120°C–150°C (250°F–300°F) after unsealing from hermetic containers. Moisture absorption causes delayed underbead cracking in high-strength steels.',
    relatedSection: '7.1.7',
    relatedSectionTitle: '7.1.7 Pre-Weld SOP'
  },
  {
    id: 'root-pass',
    term: 'Root Pass & Root Face (Land)',
    category: 'Joints & Geometry',
    standardReference: 'AWS A3.0 Standard Terms',
    definition: 'The initial weld bead laid at the very bottom or root of a joint groove connecting two structural members, bridging the root gap between the prepared root faces (lands).',
    practicalImplication: 'The most critical pass in pressure piping and full penetration groove welds. Must achieve complete penetration without burn-through (excessive drop-through) or suck-back.',
    relatedSection: '7.1.8',
    relatedSectionTitle: '7.1.8 5 Basic Joints'
  },
  {
    id: 'bevel-angle',
    term: 'Groove Bevel Angle & Included Angle',
    category: 'Joints & Geometry',
    standardReference: 'AWS D1.1 Figure 3.4',
    definition: 'The bevel angle is the angle formed between the prepared edge of a member and a plane perpendicular to the member surface. The included angle (groove angle) is the total opening angle between both bevels (typically 60°).',
    practicalImplication: 'Ensures the welder can physically fit the electrode down to the joint root with the correct travel angle to achieve complete sidewall fusion.',
    relatedSection: '7.1.8',
    relatedSectionTitle: '7.1.8 5 Basic Joints',
    keyFormulaOrMetric: 'Included Angle = 60° (Bevel = 30° each side)'
  },
  {
    id: 'lamellar-tearing',
    term: 'Lamellar Tearing',
    category: 'Joints & Geometry',
    standardReference: 'AWS D1.1 Annex E',
    definition: 'Sub-surface terrace-like cracking occurring in rolled structural steel plates subjected to high through-thickness (Z-direction) tensile residual stresses from heavy fillet or T-joint welds.',
    practicalImplication: 'Mitigated by joint redesign (e.g. corner beveling), buttering layers, or using vacuum-degassed Z-grade steels with low sulfur inclusion content.',
    relatedSection: '7.1.9',
    relatedSectionTitle: '7.1.9 Joint Uses & Merits'
  },
  {
    id: 'undercut',
    term: 'Undercut',
    category: 'Joints & Geometry',
    standardReference: 'AWS D1.1 Clause 6.12',
    definition: 'A groove melted into the base metal adjacent to the weld toe or weld root and left unfilled by weld metal.',
    practicalImplication: 'Act as a sharp stress concentration notch severely reducing dynamic fatigue life. Caused by excessive welding current, excessively long arc length, or rapid travel speed.',
    relatedSection: '7.1.2',
    relatedSectionTitle: '7.1.2 Ampere Control'
  },
  {
    id: 'inverter',
    term: 'IGBT Inverter Power Source',
    acronym: 'Inverter',
    category: 'Equipment & Components',
    standardReference: 'EN 60974-1 / AWS D1.1',
    definition: 'An advanced solid-state welding machine that rectifies line frequency AC (50/60 Hz) to DC, chops it into high-frequency AC (20 kHz–100 kHz) via Insulated Gate Bipolar Transistors (IGBT), steps it down through a miniature ferrite transformer, and re-rectifies to ultra-smooth DC.',
    practicalImplication: 'Offers >85% electrical efficiency, weighs 80% less than conventional magnetic transformers, and features microprocessor arc force/hot start dynamics.',
    relatedSection: '7.1.4',
    relatedSectionTitle: '7.1.4 5 Machine Types',
    keyFormulaOrMetric: 'Frequency: 20,000 Hz – 100,000 Hz'
  },
  {
    id: 'hot-work-permit',
    term: 'Hot Work Permit (35-Foot Rule)',
    category: 'Safety & Standards',
    standardReference: 'NFPA 51B / OSHA 1910.252',
    definition: 'A formal legal authorization issued by an authorized facility safety officer permitting temporary spark-producing operations (welding, cutting, grinding) outside a designated safe fabrication shop.',
    practicalImplication: 'Mandates clearing or shielding all combustibles within a 35-foot (10.7m) radius and posting a dedicated Fire Watch armed with an extinguisher for at least 30-60 minutes post-arc.',
    relatedSection: '7.1.7',
    relatedSectionTitle: '7.1.7 Pre-Weld SOP'
  },
  {
    id: 'arc-eye',
    term: 'Photokeratitis (Arc Eye / Welder’s Flash)',
    category: 'Safety & Standards',
    standardReference: 'ANSI Z49.1 / OSHA 1910.252',
    definition: 'Painful superficial burn injury to the cornea and conjunctiva of the eye caused by acute unprotected exposure to ultraviolet (UV-B and UV-C) radiation emitted by an electric welding arc.',
    practicalImplication: 'Symptoms (intense sand-in-eyes pain, extreme photophobia, lacrimation) usually emerge 6–12 hours post-exposure. Prevented by always wearing auto-darkening hoods with correct shade rating and ANSI Z87.1 glasses.',
    relatedSection: '7.1.7',
    relatedSectionTitle: '7.1.7 Pre-Weld SOP'
  },
  {
    id: 'marangoni-convection',
    term: 'Marangoni Convection Effect',
    category: 'Metallurgy & Consumables',
    standardReference: 'Welding Metallurgy (Sindo Kou)',
    definition: 'Thermocapillary fluid circulation in the molten weld pool driven by spatial surface tension gradients ($\partial\gamma/\partial T$).',
    practicalImplication: 'In clean steel with low sulfur, surface tension decreases with temperature, driving molten metal outward (shallow wide bead). In steel with active surfactants (sulfur/oxygen 50-150 ppm), surface tension increases with temperature, driving fluid downward into the root (deep keyhole penetration).',
    relatedSection: '7.1.6',
    relatedSectionTitle: '7.1.6 Polarity Dynamics',
    keyFormulaOrMetric: 'Fluid flow vector: dγ/dT > 0 (digging) vs dγ/dT < 0 (wide)'
  }
];

interface GlossaryProps {
  isOpen: boolean;
  onClose: () => void;
  onNavigateToSection?: (sectionId: SectionId) => void;
}

export default function TechnicalGlossary({ isOpen, onClose, onNavigateToSection }: GlossaryProps) {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('All');
  const [activeTermId, setActiveTermId] = useState<string | null>(null);

  const dialogRef = useModalA11y(onClose, isOpen);

  const categories = useMemo(() => {
    return ['All', 'Electrical Physics', 'Metallurgy & Consumables', 'Equipment & Components', 'Joints & Geometry', 'Safety & Standards'];
  }, []);

  const filteredTerms = useMemo(() => {
    return GLOSSARY_TERMS.filter(item => {
      const matchesSearch = 
        item.term.toLowerCase().includes(searchTerm.toLowerCase()) ||
        (item.acronym && item.acronym.toLowerCase().includes(searchTerm.toLowerCase())) ||
        item.definition.toLowerCase().includes(searchTerm.toLowerCase()) ||
        item.standardReference.toLowerCase().includes(searchTerm.toLowerCase());
      
      const matchesCategory = selectedCategory === 'All' || item.category === selectedCategory;
      return matchesSearch && matchesCategory;
    });
  }, [searchTerm, selectedCategory]);

  if (!isOpen) return null;

  return (
    <div 
      ref={dialogRef}
      className="fixed inset-0 z-50 overflow-hidden bg-slate-950/85 backdrop-blur-md flex justify-center items-center p-3 sm:p-6 transition-opacity animate-in fade-in duration-200"
      role="dialog"
      aria-modal="true"
      aria-labelledby="glossary-modal-title"
      tabIndex={-1}
    >
      <div className="w-full max-w-4xl bg-slate-900 border border-slate-750 rounded-2xl shadow-2xl flex flex-col max-h-[90vh] overflow-hidden">
        {/* Header */}
        <div className="bg-slate-950 px-4 sm:px-6 py-3 sm:py-4 border-b border-slate-800 flex items-center justify-between gap-3">
          <div className="flex items-center gap-2.5 sm:gap-3 min-w-0">
            <div className="w-9 h-9 sm:w-10 sm:h-10 rounded-xl bg-amber-500/20 border border-amber-500/30 flex items-center justify-center text-amber-400 shrink-0">
              <BookOpen className="w-5 h-5" />
            </div>
            <div className="min-w-0">
              <h2 id="glossary-modal-title" className="text-sm sm:text-base font-bold text-white flex items-center gap-2 truncate">
                <span>Technical Glossary</span>
                <span className="text-[10px] sm:text-[11px] font-mono font-medium px-2 py-0.5 rounded bg-slate-800 text-amber-400 border border-slate-700 shrink-0">
                  {GLOSSARY_TERMS.length} Terms
                </span>
              </h2>
              <p className="text-[10px] sm:text-xs text-slate-400 font-mono truncate">
                AWS A3.0 • AWS D1.1 • ASME IX • ISO 4063
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            aria-label="Close glossary"
            className="min-h-[44px] min-w-[44px] p-2 rounded-xl bg-slate-900 hover:bg-slate-800 active:bg-slate-750 border border-slate-800 text-slate-400 hover:text-white transition-all cursor-pointer flex items-center justify-center shrink-0 active:scale-95"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Search & Filter Bar */}
        <div className="p-3 sm:p-4 bg-slate-925 border-b border-slate-800 space-y-2.5">
          <div className="relative">
            <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              placeholder="Search terms (e.g. DCEP, OCV, HAZ, porosity)..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 focus:border-amber-500 text-xs sm:text-xs text-white rounded-xl pl-10 pr-10 py-2.5 outline-none transition-all placeholder:text-slate-500 min-h-[42px]"
            />
            {searchTerm && (
              <button
                onClick={() => setSearchTerm('')}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-white p-1.5"
              >
                <X className="w-3.5 h-3.5" />
              </button>
            )}
          </div>

          {/* Category Filter Chips */}
          <div className="flex items-center gap-1.5 overflow-x-auto pb-1 no-scrollbar">
            <Filter className="w-3.5 h-3.5 text-slate-500 shrink-0 mr-1" />
            {categories.map((cat) => (
              <button
                key={cat}
                onClick={() => setSelectedCategory(cat)}
                className={`min-h-[36px] px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap transition-all cursor-pointer shrink-0 active:scale-95 ${
                  selectedCategory === cat
                    ? 'bg-amber-500 text-slate-950 font-bold shadow-sm'
                    : 'bg-slate-800 text-slate-300 hover:text-white hover:bg-slate-750'
                }`}
              >
                {cat}
              </button>
            ))}
          </div>
        </div>

        {/* Term List Content */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-6 space-y-3">
          {filteredTerms.length === 0 ? (
            <div className="text-center py-12 text-slate-400 space-y-2">
              <Search className="w-8 h-8 mx-auto text-slate-600" />
              <p className="text-sm font-semibold text-slate-300">No matching terminology found</p>
              <p className="text-xs text-slate-500">Try adjusting your search keywords or clearing the category filter.</p>
              <button
                onClick={() => { setSearchTerm(''); setSelectedCategory('All'); }}
                className="mt-2 text-xs text-amber-400 hover:underline cursor-pointer"
              >
                Reset filters
              </button>
            </div>
          ) : (
            filteredTerms.map((item) => {
              const isExpanded = activeTermId === item.id;
              return (
                <div
                  key={item.id}
                  id={`glossary-item-${item.id}`}
                  className={`border rounded-xl transition-all ${
                    isExpanded 
                      ? 'bg-slate-850 border-amber-500/50 shadow-md' 
                      : 'bg-slate-950 border-slate-800 hover:border-slate-700'
                  }`}
                >
                  <div
                    onClick={() => setActiveTermId(isExpanded ? null : item.id)}
                    className="p-4 cursor-pointer flex flex-col sm:flex-row sm:items-center justify-between gap-2"
                  >
                    <div className="space-y-1">
                      <div className="flex flex-wrap items-center gap-2">
                        <span className="text-sm font-bold text-white tracking-tight">
                          {item.term}
                        </span>
                        {item.acronym && (
                          <span className="px-2 py-0.5 rounded bg-amber-500/10 text-amber-400 font-mono text-[11px] font-bold border border-amber-500/20">
                            {item.acronym}
                          </span>
                        )}
                        <span className="px-2 py-0.5 rounded bg-slate-800 text-slate-300 text-[10px] font-mono">
                          {item.category}
                        </span>
                      </div>
                      <p className="text-xs text-slate-400 font-mono">
                        Standard: <span className="text-slate-300">{item.standardReference}</span>
                      </p>
                    </div>

                    <div className="flex items-center gap-2 shrink-0">
                      {item.keyFormulaOrMetric && (
                        <span className="hidden md:inline-block px-2 py-1 rounded bg-slate-900 border border-slate-800 text-cyan-300 font-mono text-[11px]">
                          {item.keyFormulaOrMetric}
                        </span>
                      )}
                      <ChevronRight className={`w-4 h-4 text-slate-400 transition-transform ${isExpanded ? 'rotate-90 text-amber-400' : ''}`} />
                    </div>
                  </div>

                  {/* Expanded Content View */}
                  {isExpanded && (
                    <div className="px-4 pb-4 pt-1 border-t border-slate-800/80 space-y-3 text-xs">
                      <div>
                        <strong className="text-slate-300 font-semibold block mb-1">Standard Definition (AWS A3.0 / ISO):</strong>
                        <p className="text-slate-300 leading-relaxed bg-slate-900/70 p-3 rounded-lg border border-slate-800">
                          {item.definition}
                        </p>
                      </div>

                      <div>
                        <strong className="text-amber-300 font-semibold block mb-1">Industrial &amp; SOP Practical Implication:</strong>
                        <p className="text-slate-300 leading-relaxed bg-amber-500/5 p-3 rounded-lg border border-amber-500/20">
                          {item.practicalImplication}
                        </p>
                      </div>

                      {item.keyFormulaOrMetric && (
                        <div className="p-2.5 rounded bg-slate-900 border border-slate-800 font-mono text-[11px] text-cyan-300 flex items-center justify-between">
                          <span>Governing Equation / Metric:</span>
                          <strong className="text-cyan-400">{item.keyFormulaOrMetric}</strong>
                        </div>
                      )}

                      {item.relatedSection && onNavigateToSection && (
                        <div className="pt-2 flex justify-end">
                          <button
                            onClick={() => {
                              onNavigateToSection(item.relatedSection!);
                              onClose();
                            }}
                            className="w-full sm:w-auto min-h-[44px] px-3.5 py-2 rounded-xl bg-amber-500/20 hover:bg-amber-500/30 text-amber-300 text-xs font-bold border border-amber-500/40 flex items-center justify-center sm:justify-start gap-1.5 transition-colors cursor-pointer active:scale-95 shadow-sm"
                          >
                            <span>Open Clause: {item.relatedSectionTitle}</span>
                            <ExternalLink className="w-3.5 h-3.5 shrink-0" />
                          </button>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })
          )}
        </div>

        {/* Footer */}
        <div className="bg-slate-950 px-4 sm:px-6 py-3 border-t border-slate-800 flex items-center justify-between gap-2 text-xs text-slate-400">
          <span className="font-mono text-[10px] sm:text-[11px] truncate">
            {filteredTerms.length} of {GLOSSARY_TERMS.length} terms
          </span>
          <button
            onClick={onClose}
            className="min-h-[44px] px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 active:bg-slate-650 text-white font-bold text-xs transition-colors cursor-pointer shrink-0 active:scale-95 shadow-sm"
          >
            <span className="sm:hidden">Close</span>
            <span className="hidden sm:inline">Close Glossary</span>
          </button>
        </div>
      </div>
    </div>
  );
}
